### ISSUE TITLE
Errors with "debuild -b" command

### ISSUE THREAD

**Issue by GregorySchwing** [jvermaas/vmd-packaging-instructions#2]
```
root@3f57aa8c8953:/vmdpackaging/vmd-1.9.4a57# debuild -b
 dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package vmd
dpkg-buildpackage: info: source version 1.9.4a55-3
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by Josh Vermaas <vermaas2@illinois.edu>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: python3.8-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
```

```
root@3f57aa8c8953:/vmdpackaging/vmd-1.9.4a57# debuild -d
This package has a Debian revision number but there does not seem to be
an appropriate original tar file or .orig directory in the parent directory;
(expected one of vmd_1.9.4a55.orig.tar.gz, vmd_1.9.4a55.orig.tar.bz2,
vmd_1.9.4a55.orig.tar.lzma,  vmd_1.9.4a55.orig.tar.xz or vmd-1.9.4a57.orig)
continue anyway? (y/n) y
```

this ends up working.

The three issues I came across are 
1) python dependency problem, wants 3.8 but you install 3.10
2) revision number (perhaps this file needs to be updated changelog)
3) install command needs small change 
```
cd .. #Puts you in the right directory.
sudo dpkg -i vmd-cuda_1.9.4a57-1_amd64.deb vmd-plugins_1.9.4a55-1_amd64.deb
```
to 
```
cd .. #Puts you in the right directory.
sudo dpkg -i vmd-cuda_1.9.4a55-3_amd64.deb vmd-plugins_1.9.4a55-3_amd64.deb
```

**Comment by jvermaas** [comment]
Thanks, I originally made these instructions for a55, and it looks like when I updated to a57, a few places were left out. I think I fixed it all. Glad it was useful!

**Comment by GregorySchwing** [comment]
You didn't resolve some merge errors in the configure file.

Version control conflict marker at ./configure line 267, near "<<<<<<<"
Version control conflict marker at ./configure line 323, near "======="

**Comment by GregorySchwing** [comment]
Seems to have been some problem with all commits after the merge commit ad24a438eb95c9533a4b721c74acbcf2609235c7

The last commit to complete the build is
8e1fb095f1570824ac623695f6b76d623e0437c1

The debuild command fails to find icpc.  I wonder if it's because your new configure file requires c++11, and perhaps whatever compiler is included doesn't support it.

Since 8e1fb095f1570824ac623695f6b76d623e0437c1 builds, I'd recommend reverting the past 3 commits.

Granted the binaries are still named wrongly, 
vmd-cuda_1.9.4a55-3_amd64.deb, vmd-plugins_1.9.4a55-3_amd64.deb
instead of 
vmd-cuda_1.9.4a57-1_amd64.deb, vmd-plugins_1.9.4a57-1_amd64.deb

**Comment by jvermaas** [comment]
Thanks for this. I think I tracked it down to `debian/changelog`. I'm cautiously optimistic that I'll be able to update this properly once VMD has a newer/bigger alpha or beta release (or 24.04 comes out... We'll see which one wins).

**Comment by GregorySchwing** [comment]
you're welcome.

FYI This (https://github.com/GregorySchwing/vmd-docker) is the repo which will automate this process in docker.
The trick for development is just to edit the vmd wget with cloning your github repo/version of vmd source.
